import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:pooja_sindhu/core/constants/route_constants.dart';
import 'package:pooja_sindhu/core/theme/app_spacing.dart';
import 'package:pooja_sindhu/features/booking/presentation/providers/booking_flow_provider.dart';
import 'package:pooja_sindhu/features/booking/presentation/widgets/booking_flow_stepper.dart';
import 'package:pooja_sindhu/features/booking/presentation/widgets/slot_picker.dart';
import 'package:pooja_sindhu/shared/widgets/app_primary_button.dart';
import 'package:pooja_sindhu/shared/widgets/error_retry_view.dart';
class BookingFlowScreen extends ConsumerStatefulWidget { const BookingFlowScreen({super.key, required this.ritualId}); final String ritualId; @override ConsumerState<BookingFlowScreen> createState() => _BookingFlowScreenState(); }
class _BookingFlowScreenState extends ConsumerState<BookingFlowScreen> { @override void initState() { super.initState(); WidgetsBinding.instance.addPostFrameCallback((_) => ref.read(bookingFlowNotifierProvider.notifier).selectRitual(ritualId: widget.ritualId, ritualName: 'Selected Ritual', totalAmount: 0)); } @override Widget build(BuildContext context) { final flow = ref.watch(bookingFlowNotifierProvider); if (flow.step == BookingFlowStep.success && flow.createdBooking != null) { WidgetsBinding.instance.addPostFrameCallback((_) { ref.read(bookingFlowNotifierProvider.notifier).reset(); context.go('${Routes.bookingConfirmation}/${flow.createdBooking!.id}'); }); } final content = switch (flow.step) { BookingFlowStep.selectPandit => Center(child: AppPrimaryButton(label: 'Use Test Pandit', fullWidth: false, onPressed: () => ref.read(bookingFlowNotifierProvider.notifier).selectPandit(panditId: 'test-pandit-id', panditName: 'Test Pandit'))), BookingFlowStep.selectSlot => SlotPicker(panditId: flow.draft.panditId!, onSlotSelected: (slot) => ref.read(bookingFlowNotifierProvider.notifier).selectSlot(slot)), BookingFlowStep.review => Padding(padding: const EdgeInsets.all(AppSpacing.md), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Review your Booking', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: AppSpacing.xl), Text('Ritual: ${flow.draft.ritualName}'), Text('Pandit: ${flow.draft.panditName}'), Text('Date & Time: ${DateFormat('EEE, d MMM y • h:mm a').format(flow.draft.selectedSlot!)}'), const SizedBox(height: AppSpacing.xxl), AppPrimaryButton(label: 'Confirm & Proceed to Payment', onPressed: () => ref.read(bookingFlowNotifierProvider.notifier).confirmBooking())])), BookingFlowStep.submitting => const Center(child: CircularProgressIndicator()), BookingFlowStep.error => ErrorRetryView(message: flow.errorMessage ?? 'Something went wrong.', onRetry: () => ref.read(bookingFlowNotifierProvider.notifier).confirmBooking()), BookingFlowStep.success => const SizedBox.shrink() }; final step = switch (flow.step) { BookingFlowStep.selectPandit => 0, BookingFlowStep.selectSlot => 1, _ => 2 }; return Scaffold(appBar: AppBar(title: const Text('Book a Ritual')), body: Column(children: [BookingFlowStepper(steps: const ['Pandit', 'Date & Time', 'Review'], currentStep: step), Expanded(child: content)])); } }
