import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:pooja_sindhu/features/booking/domain/entities/booking.dart';
import 'package:pooja_sindhu/features/booking/domain/entities/booking_draft.dart';
import 'package:pooja_sindhu/features/booking/domain/usecases/create_booking.dart';
import 'package:pooja_sindhu/features/booking/presentation/providers/booking_providers.dart';
enum BookingFlowStep { selectPandit, selectSlot, review, submitting, success, error }
class BookingFlowState { const BookingFlowState({this.step = BookingFlowStep.selectPandit, this.draft = const BookingDraft(), this.createdBooking, this.errorMessage}); final BookingFlowStep step; final BookingDraft draft; final Booking? createdBooking; final String? errorMessage; BookingFlowState copyWith({BookingFlowStep? step, BookingDraft? draft, Booking? createdBooking, String? errorMessage}) => BookingFlowState(step: step ?? this.step, draft: draft ?? this.draft, createdBooking: createdBooking ?? this.createdBooking, errorMessage: errorMessage); }
class BookingFlowNotifier extends Notifier<BookingFlowState> { @override BookingFlowState build() => const BookingFlowState(); void selectRitual({required String ritualId, required String ritualName, required double totalAmount}) => state = state.copyWith(draft: state.draft.copyWith(ritualId: ritualId, ritualName: ritualName, totalAmount: totalAmount)); void selectPandit({required String panditId, required String panditName}) => state = state.copyWith(step: BookingFlowStep.selectSlot, draft: state.draft.copyWith(panditId: panditId, panditName: panditName)); void selectSlot(DateTime slot) => state = state.copyWith(step: BookingFlowStep.review, draft: state.draft.copyWith(selectedSlot: slot)); Future<void> confirmBooking() async { if (!state.draft.isReadyToConfirm) return; state = state.copyWith(step: BookingFlowStep.submitting); final result = await CreateBooking(ref.read(bookingRepositoryProvider))(state.draft); state = result.fold((failure) => state.copyWith(step: BookingFlowStep.error, errorMessage: failure.message), (booking) => state.copyWith(step: BookingFlowStep.success, createdBooking: booking)); } void reset() => state = const BookingFlowState(); }
final bookingFlowNotifierProvider = NotifierProvider<BookingFlowNotifier, BookingFlowState>(BookingFlowNotifier.new);
